/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BuilderPattern;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BuilderLaptopBuilder extends javax.swing.JFrame {

    String Brand = "N/A";
    String Model = "N/A";
    int RAM = 0;
    int GPU = 0;
    String CPU = "N/A";
    int HDD = 0;
    double Screen = 0;
    boolean WiFi = false;
    boolean Bluetooth = false;
    String OS = "N/A";

    /**
     * Creates new form BuilderLaptopBuilder
     */
    public BuilderLaptopBuilder() {

        initComponents();

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int choose = JOptionPane.showConfirmDialog(null,
                        "Do you really want to Logout ?",
                        "Confirm Logout", JOptionPane.YES_NO_OPTION,
                        JOptionPane.INFORMATION_MESSAGE);
                if (choose == JOptionPane.YES_OPTION) {
                    e.getWindow().dispose();
                    new Login().setVisible(true);
                }
            }
        });
    }

    public BuilderLaptopBuilder(String Brand, String Model, int RAM, int GPU,
            String CPU, int HDD, double Screen, boolean WiFi, boolean Bluetooth, String OS) {

        this.Brand = Brand;
        this.Model = Model;
        this.RAM = RAM;
        this.GPU = GPU;
        this.CPU = CPU;
        this.HDD = HDD;
        this.Screen = Screen;
        this.WiFi = WiFi;
        this.Bluetooth = Bluetooth;
        this.OS = OS;

    }

    @Override
    public String toString() {
        String newline = System.getProperty("line.separator");
        return "Brand: " + Brand + newline
                + "Model: " + Model + newline
                + "RAM: " + RAM + newline
                + "GPU: " + GPU + newline
                + "CPU: " + CPU + newline
                + "HDD: " + HDD + newline
                + "Screen: " + Screen + newline
                + "WiFi: " + WiFi + newline
                + "Bluetooth: " + Bluetooth + newline
                + "OS: " + OS;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProcessor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBuild = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtOS = new javax.swing.JTextField();
        comboRAM = new javax.swing.JComboBox<>();
        comboGPU = new javax.swing.JComboBox<>();
        comboHDD = new javax.swing.JComboBox<>();
        comboScreenSize = new javax.swing.JComboBox<>();
        comboWiFi = new javax.swing.JComboBox<>();
        comboBluetooth = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Laptop Builder (Builder Pattern)");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Laptop Builder");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(80, 80, 80));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Build Laptop");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Brand");

        txtBrand.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBrandKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Model");

        txtModel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModelKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RAM");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GPU");

        txtProcessor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProcessor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProcessorKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Processor");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HDD");

        btnBuild.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuild.setText("Build");
        btnBuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuildActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Screen SIze");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("WiFI");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bluetooth");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("OS");

        txtOS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOSActionPerformed(evt);
            }
        });

        comboRAM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboRAM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "4GB", "8GB", "16GB", "32GB", "64GB" }));
        comboRAM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboRAMKeyPressed(evt);
            }
        });

        comboGPU.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboGPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2GB", "4GB", "8GB", "16GB", "32GB" }));
        comboGPU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboGPUKeyPressed(evt);
            }
        });

        comboHDD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboHDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "128GB", "512GB", "1TB", "2TB", "4TB" }));
        comboHDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboHDDKeyPressed(evt);
            }
        });

        comboScreenSize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboScreenSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "11.6", "13.3", "14", "15.6", "17" }));
        comboScreenSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboScreenSizeKeyPressed(evt);
            }
        });

        comboWiFi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboWiFi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Yes", "No" }));
        comboWiFi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboWiFiKeyPressed(evt);
            }
        });

        comboBluetooth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBluetooth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Yes", "No" }));
        comboBluetooth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboBluetoothKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProcessor)
                                    .addComponent(txtModel)
                                    .addComponent(txtOS, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboRAM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboGPU, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboHDD, javax.swing.GroupLayout.Alignment.TRAILING, 0, 136, Short.MAX_VALUE)
                                    .addComponent(comboScreenSize, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboWiFi, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBluetooth, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnBuild, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboGPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProcessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboHDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboScreenSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboWiFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboBluetooth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuild)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data");

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Model", "RAM", "GPU", "CPU", "HDD", "Screen", "WiFi", "BT", "OS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(846, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuildActionPerformed

        BuildLaptop();
        InsertDataToTable();
    }//GEN-LAST:event_btnBuildActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        String newline = System.getProperty("line.separator");

        String f1 = ((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        String f2 = ((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
        String f3 = ((String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2))));
        String f4 = ((String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 3))));
        String f5 = ((String) jTable1.getValueAt(jTable1.getSelectedRow(), 4));
        String f6 = ((String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 5))));
        String f7 = ((String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 6))));
        String f8 = ((String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 7))));
        String f9 = ((String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 8))));
        String f10 = ((String) jTable1.getValueAt(jTable1.getSelectedRow(), 9));

        String row = "Brand: " + f1 + newline
                + "Model: " + f2 + newline
                + "RAM: " + f3 + newline
                + "GPU: " + f4 + newline
                + "CPU: " + f5 + newline
                + "HDD: " + f6 + newline
                + "Screen: " + f7 + newline
                + "WiFi: " + f8 + newline
                + "Bluetooth: " + f9 + newline
                + "OS: " + f10;

        JOptionPane.showMessageDialog(this, row);

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtBrandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrandKeyPressed
        if (evt.getKeyCode() == 10) {
            txtModel.grabFocus();
        }
    }//GEN-LAST:event_txtBrandKeyPressed

    private void txtModelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyPressed
        if (evt.getKeyCode() == 10) {
            comboRAM.setPopupVisible(true);
            comboRAM.grabFocus();
        }
    }//GEN-LAST:event_txtModelKeyPressed

    private void comboRAMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboRAMKeyPressed
        if (evt.getKeyCode() == 10) {
            comboGPU.setPopupVisible(true);
            comboGPU.grabFocus();
        }
    }//GEN-LAST:event_comboRAMKeyPressed

    private void comboGPUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboGPUKeyPressed
        if (evt.getKeyCode() == 10) {
            txtProcessor.grabFocus();
        }
    }//GEN-LAST:event_comboGPUKeyPressed

    private void txtProcessorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcessorKeyPressed
        if (evt.getKeyCode() == 10) {
            comboHDD.setPopupVisible(true);
            comboHDD.grabFocus();
        }
    }//GEN-LAST:event_txtProcessorKeyPressed

    private void comboHDDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboHDDKeyPressed
        if (evt.getKeyCode() == 10) {
            comboScreenSize.setPopupVisible(true);
            comboScreenSize.grabFocus();
        }
    }//GEN-LAST:event_comboHDDKeyPressed

    private void comboScreenSizeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboScreenSizeKeyPressed
        if (evt.getKeyCode() == 10) {
            comboWiFi.setPopupVisible(true);
            comboWiFi.grabFocus();
        }
    }//GEN-LAST:event_comboScreenSizeKeyPressed

    private void comboWiFiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboWiFiKeyPressed
        if (evt.getKeyCode() == 10) {
            comboBluetooth.setPopupVisible(true);
            comboBluetooth.grabFocus();
        }
    }//GEN-LAST:event_comboWiFiKeyPressed

    private void comboBluetoothKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBluetoothKeyPressed
        if (evt.getKeyCode() == 10) {
            txtOS.grabFocus();
        }
    }//GEN-LAST:event_comboBluetoothKeyPressed

    private void txtOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOSActionPerformed
        BuildLaptop();
        InsertDataToTable();
    }//GEN-LAST:event_txtOSActionPerformed

    private void BuildLaptop() {
        if ("".equals(txtBrand.getText())) {
            Brand = "N/A";
        } else {
            Brand = txtBrand.getText();
        }

        if ("".equals(txtModel.getText())) {
            Model = "N/A";
        } else {
            Model = txtModel.getText();
        }

        if (comboRAM.getSelectedItem() == "4GB") {
            RAM = 4;
        } else if ((comboRAM.getSelectedItem() == "8GB")) {
            RAM = 8;
        } else if ((comboRAM.getSelectedItem() == "16GB")) {
            RAM = 16;
        } else if ((comboRAM.getSelectedItem() == "32GB")) {
            RAM = 32;
        } else if ((comboRAM.getSelectedItem() == "64GB")) {
            RAM = 64;
        }

        if (comboGPU.getSelectedItem() == "2GB") {
            GPU = 2;
        } else if ((comboGPU.getSelectedItem() == "4GB")) {
            GPU = 4;
        } else if ((comboGPU.getSelectedItem() == "8GB")) {
            GPU = 8;
        } else if ((comboGPU.getSelectedItem() == "16GB")) {
            GPU = 16;
        } else if ((comboGPU.getSelectedItem() == "32GB")) {
            GPU = 32;
        }

        if ("".equals(txtProcessor.getText())) {
            CPU = "N/A";
        } else {
            CPU = txtProcessor.getText();
        }

        if (comboHDD.getSelectedItem() == "128GB") {
            HDD = 128;
        } else if ((comboHDD.getSelectedItem() == "256GB")) {
            HDD = 256;
        } else if ((comboHDD.getSelectedItem() == "512GB")) {
            HDD = 512;
        } else if ((comboHDD.getSelectedItem() == "1TB")) {
            HDD = 1;
        } else if ((comboHDD.getSelectedItem() == "2TB")) {
            HDD = 2;
        } else if ((comboHDD.getSelectedItem() == "4TB")) {
            HDD = 4;
        }

        if (comboScreenSize.getSelectedItem() == "11.6") {
            Screen = 11.6;
        } else if ((comboScreenSize.getSelectedItem() == "13.3")) {
            Screen = 13.3;
        } else if ((comboScreenSize.getSelectedItem() == "14")) {
            Screen = 14;
        } else if ((comboScreenSize.getSelectedItem() == "15.6")) {
            Screen = 15.6;
        } else if ((comboScreenSize.getSelectedItem() == "17")) {
            Screen = 17;
        }

        if (comboWiFi.getSelectedItem() == "Yes") {
            WiFi = true;
        } else {
            WiFi = false;
        }

        Bluetooth = comboBluetooth.getSelectedItem() == "Yes";

        if ("".equals(txtOS.getText())) {
            OS = "N/A";
        } else {
            OS = txtOS.getText();
        }

        BuilderLaptopBuilder laptop = new Laptop()
                .setBrand(Brand)
                .setModel(Model)
                .setRAM(RAM)
                .setGPU(GPU)
                .setCPU(CPU)
                .setHDD(HDD)
                .setScreen(Screen)
                .setWiFi(WiFi)
                .setBluetooth(Bluetooth)
                .setOS(OS)
                .getLaptop();
        JOptionPane.showMessageDialog(this, laptop.toString());
    }

    private void InsertDataToTable() {

        if (isDataFilled()) {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.addRow(new Object[]{Brand, Model, RAM, GPU, CPU, HDD, Screen, WiFi, Bluetooth, OS});
            JOptionPane.showMessageDialog(null, "New Row Added!");
            txtBrand.grabFocus();

            txtBrand.setText("");
            txtModel.setText("");
            comboRAM.setSelectedIndex(0);
            comboGPU.setSelectedIndex(0);
            txtProcessor.setText("");
            comboHDD.setSelectedIndex(0);
            comboScreenSize.setSelectedIndex(0);
            comboWiFi.setSelectedIndex(0);
            comboBluetooth.setSelectedIndex(0);
            txtOS.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Please fill all the data to continue!");

        }
    }

    boolean isDataFilled() {
        if (!txtBrand.getText().equals("")
                || !txtModel.getText().equals("")
                || !comboRAM.getSelectedItem().equals("Select")
                || !comboGPU.getSelectedItem().equals("Select")
                || !txtProcessor.getText().equals("")
                || !comboHDD.getSelectedItem().equals("Select")
                || !comboScreenSize.getSelectedItem().equals("Select")
                || !comboWiFi.getSelectedItem().equals("Select")
                || !comboBluetooth.getSelectedItem().equals("Select")
                || !txtOS.equals("")) {

            return true;
        } else {
            return false;
        }
    }

    class Laptop {

        private String Brand;
        private String Model;
        private int RAM;
        private int GPU;
        private String CPU;
        private int HDD;
        private double Screen;
        private boolean WiFi;
        private boolean Bluetooth;
        private String OS;

        public Laptop setBrand(String Brand) {
            this.Brand = Brand;
            return this;
        }

        public Laptop setModel(String Model) {
            this.Model = Model;
            return this;
        }

        public Laptop setRAM(int RAM) {
            this.RAM = RAM;
            return this;
        }

        public Laptop setGPU(int GPU) {
            this.GPU = GPU;
            return this;
        }

        public Laptop setCPU(String CPU) {
            this.CPU = CPU;
            return this;
        }

        public Laptop setHDD(int HDD) {
            this.HDD = HDD;
            return this;
        }

        public Laptop setScreen(double Screen) {
            this.Screen = Screen;
            return this;
        }

        public Laptop setWiFi(boolean WiFi) {
            this.WiFi = WiFi;
            return this;
        }

        public Laptop setBluetooth(boolean Bluetooth) {
            this.Bluetooth = Bluetooth;
            return this;
        }

        public Laptop setOS(String OS) {
            this.OS = OS;
            return this;
        }

        public BuilderLaptopBuilder getLaptop() {
            return new BuilderLaptopBuilder(Brand, Model, RAM, GPU, CPU, HDD,
                    Screen, WiFi, Bluetooth, OS);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuilderLaptopBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuilderLaptopBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuilderLaptopBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuilderLaptopBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuilderLaptopBuilder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuild;
    private javax.swing.JComboBox<String> comboBluetooth;
    private javax.swing.JComboBox<String> comboGPU;
    private javax.swing.JComboBox<String> comboHDD;
    private javax.swing.JComboBox<String> comboRAM;
    private javax.swing.JComboBox<String> comboScreenSize;
    private javax.swing.JComboBox<String> comboWiFi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOS;
    private javax.swing.JTextField txtProcessor;
    // End of variables declaration//GEN-END:variables
}
